import "@/app/globals.css";
import { Inter } from "next/font/google";
import { ClientSession } from "@/app/session-provider";
import { auth } from '@/auth'
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Blog",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await auth()

    return (
        <html lang="en">
            <body className={`${inter.className} min-h-screen flex flex-col`}>
                <ClientSession>
                    <Header session={session} />
                    {children}
                </ClientSession>
            </body>
        </html>
    );
}
